[project]
name = "openrouter-and-litellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.5.5",
    "litellm>=1.73.6",
    "openai-agents[litellm]>=0.1.0",
]
